name: massai mara park 01 gradle multiple jobs
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4

      - run: chmod +x gradlew
      - run: ./gradlew clean bootJar --no-daemon

      # ⬇️ JAR 를 아티팩트로 업로드
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

  deploy_and_test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: .

      # 애플리케이션 백그라운드 실행
      - name: Run app
        run: |
          java -jar *.jar --server.port=8080 &
          echo $! > app.pid

      # 포트 열릴 때까지 대기
      - name: Wait until healthy
        run: |
          for i in {1..20}; do
            curl -fs http://localhost:8080/actuator/health && exit 0
            sleep 3
          done
          echo "App failed to start" && cat app.pid && exit 1

      # 통합 테스트
      - name: Test #1
        run: curl -f http://localhost:8080/
      - name: Test #2
        run: curl -f http://localhost:8080/images
      - name: Test #3
        run: curl -f http://localhost:8080/animal

      # 항상 프로세스 종료
      - name: Stop app
        if: always()
        run: kill $(cat app.pid) || true
