name: Test EC2 Connection with GHA

on:
    workflow_dispatch:

env:
    EC2_HOSTNAME: 192.168.127.129
    EC2_USER_NAME: ubuntu

jobs:
  testec2-connect:
    name: test ec2 connection
    runs-on: ubuntu-22.04

    steps:
      - name: Setup SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add private key
        run: |
          echo "${{ secrets.EC2_PRIVATEKEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Test SSH connection
        run: |
          echo "SSH 연결 테스트 시작..."

          ssh -vvv -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -i ~/.ssh/ec2_key -p 22 \
              ${{ env.EC2_USER_NAME }}@${{ env.EC2_HOSTNAME }} <<'EOF'
                echo "현재 사용자: $(whoami)"
                echo "호스트명: $(hostname)"
          EOF

          echo "SSH 연결 테스트 끝!"

      - name: upload README.md via SCP
        run:
            echo "Hello, EC@ SCP" > README.md

            scp -i ~/.ssh/ec2_key \
            -o "StrictHostKeyChecking=no" \
            -o "UserKnownHostsFile=/dev/null" \
            -P 22 README.md \
            ubuntu@192.168.127.129:~/

      - name: cleanup private key
        if: always()
        run: |
          rm -f ~/.ssh/ec2_key
