name: Test EC2 Connection with GHA

on:
  workflow_dispatch:

jobs:
  testec2-connect:
    name: test ec2 connection
    runs-on: ubuntu-22.04

    steps:
      - name: Setup SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add private key
        run: |
          echo "${{ secrets.EC2_PRIVATEKEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Test SSH connection
        env:
          HOSTNAME: ubuntu
          USER_NAME: ubuntu
        run: |
          echo "SSH 연결 테스트 시작..."

          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -i ~/.ssh/ec2_key -p 22 \
              ${{ env.USER_NAME }}@${{ env.HOSTNAME }} <<'EOF'
                echo "현재 사용자: $(whoami)"
                echo "호스트명: $(hostname)"
          EOF

          echo "SSH 연결 테스트 끝!"

      - name: Cleanup private key
        if: always()
        run: |
          rm -f ~/.ssh/ec2_key
